version: "3"

services:
  zookeeper:
    image: myimage
    hostname: zookeeper
    command: >
      /bin/bash -c "
      sed -i 's/localhost:9092/kafka:9092/' config/zookeeper.properties;
      bin/zookeeper-server-start.sh config/zookeeper.properties;"
  kafka:
    image: myimage
    hostname: kafka
    command: >
      /bin/bash -c "
      sed -i 's/localhost:2181/zookeeper:2181/' config/server.properties;
      bin/kafka-server-start.sh config/server.properties;"
  producer:
    image: myimage
    command: >
      /bin/bash -c "
      while ! nc -z kafka 9092;
      do
        echo Waiting for 9092 port to be accessible;
        sleep 5;
      done;
      bin/kafka-topics.sh --create --topic mytopic --bootstrap-server kafka:9092;
      python3 producer.py;"
  consumer:
    image: myimage
    command: >
      /bin/bash -c "
      while ! nc -z kafka 9092;
      do
        echo Waiting for 9092 port to be accessible;
        sleep 5;
      done;
      python3 consumer.py;"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
